{
  "document_title": "CVE-2023-26303",
  "document_type": "SUSE CVE",
  "document_publisher": {
    "type": "Vendor",
    "contact_details": "security@suse.de",
    "issuing_authority": "SUSE Security Team"
  },
  "document_tracking": {
    "identification": {
      "id": "SUSE CVE-2023-26303"
    },
    "status": "Interim",
    "version": "1",
    "revision_history": {
      "revision": {
        "number": "2",
        "date": "2023-03-10T00:15:23Z",
        "description": "current"
      }
    },
    "initial_release_date": "2023-03-07T00:14:08Z",
    "current_release_date": "2023-03-10T00:15:23Z",
    "generator": {
      "engine": "cve-database/bin/generate-cvrf-cve.pl",
      "date": "2020-12-27T01:00:00Z"
    }
  },
  "document_notes": [
    {
      "text": "CVE-2023-26303",
      "title": "CVE",
      "type": "Summary"
    },
    {
      "text": "Denial of service could be caused to markdown-it-py, before v2.2.0, if an attacker was allowed to force null assertions with specially crafted input.",
      "title": "Mitre CVE Description",
      "type": "Description"
    },
    {
      "text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "title": "Terms of Use",
      "type": "Legal Disclaimer"
    }
  ],
  "document_references": [
    {
      "type": "Self",
      "url": "https://www.suse.com/support/security/rating/",
      "description": "SUSE Security Ratings"
    }
  ],
  "product_tree": {
    "branch": [
      {
        "type": "Product Family",
        "name": "openSUSE Tumbleweed",
        "branch": [
          {
            "type": "Product Name",
            "name": "openSUSE Tumbleweed",
            "full_product_name": {
              "text": "openSUSE Tumbleweed",
              "product_id": "openSUSE Tumbleweed",
              "cpe": "cpe:/o:opensuse:tumbleweed"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Version",
        "name": "python310-markdown-it-py-2.2.0-1.1",
        "full_product_name": {
          "text": "python310-markdown-it-py-2.2.0-1.1",
          "product_id": "python310-markdown-it-py-2.2.0-1.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python311-markdown-it-py-2.2.0-1.1",
        "full_product_name": {
          "text": "python311-markdown-it-py-2.2.0-1.1",
          "product_id": "python311-markdown-it-py-2.2.0-1.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python38-markdown-it-py-2.2.0-1.1",
        "full_product_name": {
          "text": "python38-markdown-it-py-2.2.0-1.1",
          "product_id": "python38-markdown-it-py-2.2.0-1.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python39-markdown-it-py-2.2.0-1.1",
        "full_product_name": {
          "text": "python39-markdown-it-py-2.2.0-1.1",
          "product_id": "python39-markdown-it-py-2.2.0-1.1"
        }
      }
    ],
    "relationship": [
      {
        "product_reference": "python310-markdown-it-py-2.2.0-1.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      },
      {
        "product_reference": "python311-markdown-it-py-2.2.0-1.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      },
      {
        "product_reference": "python38-markdown-it-py-2.2.0-1.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      },
      {
        "product_reference": "python39-markdown-it-py-2.2.0-1.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      }
    ]
  },
  "vulnerability": {
    "notes": [
      {
        "text": "Denial of service could be caused to markdown-it-py, before v2.2.0, if an attacker was allowed to force null assertions with specially crafted input.",
        "title": "Vulnerability Description",
        "type": "General"
      }
    ],
    "cve": "CVE-2023-26303",
    "product_statuses": [
      {
        "type": "Fixed",
        "product_id": [
          "openSUSE Tumbleweed:python310-markdown-it-py-2.2.0-1.1",
          "openSUSE Tumbleweed:python311-markdown-it-py-2.2.0-1.1",
          "openSUSE Tumbleweed:python38-markdown-it-py-2.2.0-1.1",
          "openSUSE Tumbleweed:python39-markdown-it-py-2.2.0-1.1"
        ]
      }
    ],
    "threats": [
      {
        "type": "Impact",
        "description": "low"
      }
    ],
    "cvss_score_sets": {
      "score_set_v_2": {},
      "score_set_v_3": {
        "base_score_v_3": "3.3",
        "vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L"
      }
    }
  }
}
