{
	"document_title": "CVE-2014-3730",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2014-3730"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "10",
				"date": "2023-02-12T02:41:06Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-05-30T13:21:34Z",
		"current_release_date": "2023-02-12T02:41:06Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2014-3730",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by \"http:\\\\\\djangoproject.com.\"",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2014-June/000894.html",
			"description": "E-Mail link for SUSE-SU-2014:0851-1"
		},
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html",
			"description": "E-Mail link for openSUSE-SU-2014:1132-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud 3.0",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud 3.0",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud 3.0",
							"product_id": "SUSE OpenStack Cloud 3.0"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-django-1.5.8-0.7.1",
				"full_product_name": {
					"text": "python-django-1.5.8-0.7.1",
					"product_id": "python-django-1.5.8-0.7.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-django-1.5.8-0.7.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud 3.0"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by \"http:\\\\\\djangoproject.com.\"",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2014-3730",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE OpenStack Cloud 3.0:python-django-1.5.8-0.7.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.3",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {}
			}
		}
	]
}
