{
	"document_title": "CVE-2024-38875",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2024-38875"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "3",
				"date": "2024-07-17T23:10:41Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-07-09T23:10:16Z",
		"current_release_date": "2024-07-17T23:10:41Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2024-38875",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2024-July/018995.html",
			"description": "E-Mail link for SUSE-SU-2024:2545-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
							"product_id": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
							"cpe": "cpe:/o:suse:packagehub:15:sp6"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.5",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.5",
						"full_product_name": {
							"text": "openSUSE Leap 15.5",
							"product_id": "openSUSE Leap 15.5",
							"cpe": "cpe:/o:opensuse:leap:15.5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.6",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.6",
						"full_product_name": {
							"text": "openSUSE Leap 15.6",
							"product_id": "openSUSE Leap 15.6",
							"cpe": "cpe:/o:opensuse:leap:15.6"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-Django",
				"full_product_name": {
					"text": "python-Django",
					"product_id": "python-Django"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-Django",
				"full_product_name": {
					"text": "python3-Django",
					"product_id": "python3-Django"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-Django-2.0.7-150000.1.20.1",
				"full_product_name": {
					"text": "python3-Django-2.0.7-150000.1.20.1",
					"product_id": "python3-Django-2.0.7-150000.1.20.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-Django",
				"full_product_name": {
					"text": "python311-Django",
					"product_id": "python311-Django"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-Django-4.2.11-150600.3.3.1",
				"full_product_name": {
					"text": "python311-Django-4.2.11-150600.3.3.1",
					"product_id": "python311-Django-4.2.11-150600.3.3.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python3-Django-2.0.7-150000.1.20.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.5"
			},
			{
				"product_reference": "python311-Django-4.2.11-150600.3.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Package Hub 15 SP6"
			},
			{
				"product_reference": "python311-Django-4.2.11-150600.3.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.6"
			},
			{
				"product_reference": "python311-Django",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Package Hub 15 SP6"
			},
			{
				"product_reference": "python-Django",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Package Hub 15 SP6"
			},
			{
				"product_reference": "python3-Django",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.5"
			},
			{
				"product_reference": "python-Django",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.5"
			},
			{
				"product_reference": "python311-Django",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.6"
			},
			{
				"product_reference": "python-Django",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.6"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-38875",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.5:python3-Django-2.0.7-150000.1.20.1"
					]
				},
				{
					"type": "First Fixed",
					"product_id": [
						"SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.3.1",
						"openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.3.1"
					]
				},
				{
					"type": "Known Affected",
					"product_id": [
						"SUSE Linux Enterprise Module for Package Hub 15 SP6:python-Django",
						"SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django",
						"openSUSE Leap 15.5:python-Django",
						"openSUSE Leap 15.5:python3-Django",
						"openSUSE Leap 15.6:python-Django",
						"openSUSE Leap 15.6:python311-Django"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			}
		}
	]
}
