{
	"document_title": "CVE-2016-9014",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2016-9014"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "12",
				"date": "2023-02-10T02:29:06Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-05-30T13:47:14Z",
		"current_release_date": "2023-02-10T02:29:06Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2016-9014",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "Django before 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3, when settings.DEBUG is True, allow remote attackers to conduct DNS rebinding attacks by leveraging failure to validate the HTTP Host header against settings.ALLOWED_HOSTS.",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003895.html",
			"description": "E-Mail link for SUSE-SU-2018:0973-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003965.html",
			"description": "E-Mail link for SUSE-SU-2018:1102-1"
		},
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/opensuse-updates/2018-03/msg00103.html",
			"description": "E-Mail link for openSUSE-SU-2018:0824-1"
		},
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/opensuse-updates/2018-03/msg00105.html",
			"description": "E-Mail link for openSUSE-SU-2018:0826-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud 6",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud 6",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud 6",
							"product_id": "SUSE OpenStack Cloud 6",
							"cpe": "cpe:/o:suse:suse-openstack-cloud:6"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud 7",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud 7",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud 7",
							"product_id": "SUSE OpenStack Cloud 7",
							"cpe": "cpe:/o:suse:suse-openstack-cloud:7"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.8.19-3.4.1",
				"full_product_name": {
					"text": "python-Django-1.8.19-3.4.1",
					"product_id": "python-Django-1.8.19-3.4.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.8.19-3.6.1",
				"full_product_name": {
					"text": "python-Django-1.8.19-3.6.1",
					"product_id": "python-Django-1.8.19-3.6.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-Django-1.8.19-3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud 6"
			},
			{
				"product_reference": "python-Django-1.8.19-3.4.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "Django before 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3, when settings.DEBUG is True, allow remote attackers to conduct DNS rebinding attacks by leveraging failure to validate the HTTP Host header against settings.ALLOWED_HOSTS.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2016-9014",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1",
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.4.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "low"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4",
					"vector_v_2": "AV:N/AC:H/Au:N/C:P/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "8.1",
					"vector_v_3": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
				}
			}
		}
	]
}
