{
  "document_title": "CVE-2020-36599",
  "document_type": "SUSE CVE",
  "document_publisher": {
    "type": "Vendor",
    "contact_details": "security@suse.de",
    "issuing_authority": "SUSE Security Team"
  },
  "document_tracking": {
    "identification": {
      "id": "SUSE CVE-2020-36599"
    },
    "status": "Interim",
    "version": "1",
    "revision_history": {
      "revision": {
        "number": "1",
        "date": "2022-08-20T00:06:37Z",
        "description": "current"
      }
    },
    "initial_release_date": "2022-08-20T00:06:37Z",
    "current_release_date": "2022-08-20T00:06:37Z",
    "generator": {
      "engine": "cve-database/bin/generate-cvrf-cve.pl",
      "date": "2020-12-27T01:00:00Z"
    }
  },
  "document_notes": [
    {
      "text": "CVE-2020-36599",
      "title": "CVE",
      "type": "Summary"
    },
    {
      "text": "lib/omniauth/failure_endpoint.rb in OmniAuth before 1.9.2 (and before 2.0) does not escape the message_key value.",
      "title": "Mitre CVE Description",
      "type": "Description"
    },
    {
      "text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "title": "Terms of Use",
      "type": "Legal Disclaimer"
    }
  ],
  "document_references": [
    {
      "type": "Self",
      "url": "https://www.suse.com/support/security/rating/",
      "description": "SUSE Security Ratings"
    }
  ],
  "product_tree": {},
  "vulnerability": {
    "notes": [
      {
        "text": "lib/omniauth/failure_endpoint.rb in OmniAuth before 1.9.2 (and before 2.0) does not escape the message_key value.",
        "title": "Vulnerability Description",
        "type": "General"
      }
    ],
    "cve": "CVE-2020-36599",
    "threats": [
      {
        "type": "Impact",
        "description": "critical"
      }
    ],
    "cvss_score_sets": {
      "score_set_v_2": {},
      "score_set_v_3": {
        "base_score_v_3": "9.8",
        "vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
      }
    }
  }
}
