{
  "document_title": "CVE-2021-41213",
  "document_type": "SUSE CVE",
  "document_publisher": {
    "type": "Vendor",
    "contact_details": "security@suse.de",
    "issuing_authority": "SUSE Security Team"
  },
  "document_tracking": {
    "identification": {
      "id": "SUSE CVE-2021-41213"
    },
    "status": "Interim",
    "version": "1",
    "revision_history": {
      "revision": {
        "number": "3",
        "date": "2022-10-21T23:47:01Z",
        "description": "current"
      }
    },
    "initial_release_date": "2021-11-09T02:08:28Z",
    "current_release_date": "2022-10-21T23:47:01Z",
    "generator": {
      "engine": "cve-database/bin/generate-cvrf-cve.pl",
      "date": "2020-12-27T01:00:00Z"
    }
  },
  "document_notes": [
    {
      "text": "CVE-2021-41213",
      "title": "CVE",
      "type": "Summary"
    },
    {
      "text": "TensorFlow is an open source platform for machine learning. In affected versions the code behind `tf.function` API can be made to deadlock when two `tf.function` decorated Python functions are mutually recursive. This occurs due to using a non-reentrant `Lock` Python object. Loading any model which contains mutually recursive functions is vulnerable. An attacker can cause denial of service by causing users to load such models and calling a recursive `tf.function`, although this is not a frequent scenario. The fix will be included in TensorFlow 2.7.0. We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4, as these are also affected and still in supported range.",
      "title": "Mitre CVE Description",
      "type": "Description"
    },
    {
      "text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "title": "Terms of Use",
      "type": "Legal Disclaimer"
    }
  ],
  "document_references": [
    {
      "type": "Self",
      "url": "https://www.suse.com/support/security/rating/",
      "description": "SUSE Security Ratings"
    }
  ],
  "product_tree": {
    "branch": [
      {
        "type": "Product Family",
        "name": "openSUSE Tumbleweed",
        "branch": [
          {
            "type": "Product Name",
            "name": "openSUSE Tumbleweed",
            "full_product_name": {
              "text": "openSUSE Tumbleweed",
              "product_id": "openSUSE Tumbleweed",
              "cpe": "cpe:/o:opensuse:tumbleweed"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Version",
        "name": "tensorflow-lite-2.9.1-1.1",
        "full_product_name": {
          "text": "tensorflow-lite-2.9.1-1.1",
          "product_id": "tensorflow-lite-2.9.1-1.1"
        }
      },
      {
        "type": "Product Version",
        "name": "tensorflow-lite-devel-2.9.1-1.1",
        "full_product_name": {
          "text": "tensorflow-lite-devel-2.9.1-1.1",
          "product_id": "tensorflow-lite-devel-2.9.1-1.1"
        }
      }
    ],
    "relationship": [
      {
        "product_reference": "tensorflow-lite-2.9.1-1.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      },
      {
        "product_reference": "tensorflow-lite-devel-2.9.1-1.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      }
    ]
  },
  "vulnerability": {
    "notes": [
      {
        "text": "TensorFlow is an open source platform for machine learning. In affected versions the code behind `tf.function` API can be made to deadlock when two `tf.function` decorated Python functions are mutually recursive. This occurs due to using a non-reentrant `Lock` Python object. Loading any model which contains mutually recursive functions is vulnerable. An attacker can cause denial of service by causing users to load such models and calling a recursive `tf.function`, although this is not a frequent scenario. The fix will be included in TensorFlow 2.7.0. We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4, as these are also affected and still in supported range.",
        "title": "Vulnerability Description",
        "type": "General"
      }
    ],
    "cve": "CVE-2021-41213",
    "product_statuses": [
      {
        "type": "Fixed",
        "product_id": [
          "openSUSE Tumbleweed:tensorflow-lite-2.9.1-1.1",
          "openSUSE Tumbleweed:tensorflow-lite-devel-2.9.1-1.1"
        ]
      }
    ],
    "threats": [
      {
        "type": "Impact",
        "description": "important"
      }
    ],
    "cvss_score_sets": {
      "score_set_v_2": {
        "base_score_v_2": "4.3",
        "vector_v_2": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
      },
      "score_set_v_3": {
        "base_score_v_3": "5.5",
        "vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
      }
    }
  }
}
