{
  "document_title": "CVE-2013-1443",
  "document_type": "SUSE CVE",
  "document_publisher": {
    "type": "Vendor",
    "contact_details": "security@suse.de",
    "issuing_authority": "SUSE Security Team"
  },
  "document_tracking": {
    "identification": {
      "id": "SUSE CVE-2013-1443"
    },
    "status": "Interim",
    "version": "1",
    "revision_history": {
      "revision": {
        "number": "9",
        "date": "2022-10-15T17:39:29Z",
        "description": "current"
      }
    },
    "initial_release_date": "2021-05-30T13:09:40Z",
    "current_release_date": "2022-10-15T17:39:29Z",
    "generator": {
      "engine": "cve-database/bin/generate-cvrf-cve.pl",
      "date": "2020-12-27T01:00:00Z"
    }
  },
  "document_notes": [
    {
      "text": "CVE-2013-1443",
      "title": "CVE",
      "type": "Summary"
    },
    {
      "text": "The authentication framework (django.contrib.auth) in Django 1.4.x before 1.4.8, 1.5.x before 1.5.4, and 1.6.x before 1.6 beta 4 allows remote attackers to cause a denial of service (CPU consumption) via a long password which is then hashed.",
      "title": "Mitre CVE Description",
      "type": "Description"
    },
    {
      "text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "title": "Terms of Use",
      "type": "Legal Disclaimer"
    }
  ],
  "document_references": [
    {
      "type": "Self",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2013-November/000633.html",
      "description": "E-Mail link for SUSE-SU-2013:1665-1"
    },
    {
      "type": "Self",
      "url": "https://lists.opensuse.org/opensuse-updates/2013-09/msg00056.html",
      "description": "E-Mail link for openSUSE-SU-2013:1492-1"
    },
    {
      "type": "Self",
      "url": "https://lists.opensuse.org/opensuse-updates/2013-10/msg00015.html",
      "description": "E-Mail link for openSUSE-SU-2013:1541-1"
    },
    {
      "type": "Self",
      "url": "https://lists.opensuse.org/opensuse-updates/2013-11/msg00035.html",
      "description": "E-Mail link for openSUSE-SU-2013:1685-1"
    },
    {
      "type": "Self",
      "url": "https://www.suse.com/support/security/rating/",
      "description": "SUSE Security Ratings"
    }
  ],
  "product_tree": {
    "branch": [
      {
        "type": "Product Family",
        "name": "SUSE OpenStack Cloud 2.0",
        "branch": [
          {
            "type": "Product Name",
            "name": "SUSE OpenStack Cloud 2.0",
            "full_product_name": {
              "text": "SUSE OpenStack Cloud 2.0",
              "product_id": "SUSE OpenStack Cloud 2.0"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Version",
        "name": "python-django-1.4.8-0.8.1",
        "full_product_name": {
          "text": "python-django-1.4.8-0.8.1",
          "product_id": "python-django-1.4.8-0.8.1"
        }
      }
    ],
    "relationship": [
      {
        "product_reference": "python-django-1.4.8-0.8.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "SUSE OpenStack Cloud 2.0"
      }
    ]
  },
  "vulnerability": {
    "notes": [
      {
        "text": "The authentication framework (django.contrib.auth) in Django 1.4.x before 1.4.8, 1.5.x before 1.5.4, and 1.6.x before 1.6 beta 4 allows remote attackers to cause a denial of service (CPU consumption) via a long password which is then hashed.",
        "title": "Vulnerability Description",
        "type": "General"
      }
    ],
    "cve": "CVE-2013-1443",
    "product_statuses": [
      {
        "type": "Fixed",
        "product_id": [
          "SUSE OpenStack Cloud 2.0:python-django-1.4.8-0.8.1"
        ]
      }
    ],
    "threats": [
      {
        "type": "Impact",
        "description": "moderate"
      }
    ],
    "cvss_score_sets": {
      "score_set_v_2": {
        "base_score_v_2": "5",
        "vector_v_2": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
      },
      "score_set_v_3": {}
    }
  }
}
