{
	"document_title": "CVE-2013-2132",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2013-2132"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "14",
				"date": "2023-12-08T02:40:29Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-05-30T13:11:36Z",
		"current_release_date": "2023-12-08T02:40:29Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2013-2132",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "bson/_cbsonmodule.c in the mongo-python-driver (aka. pymongo) before 2.5.2, as used in MongoDB, allows context-dependent attackers to cause a denial of service (NULL pointer dereference and crash) via vectors related to decoding of an \"invalid DBRef.\"",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
						"full_product_name": {
							"text": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
							"product_id": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
							"cpe": "cpe:/o:suse:suse-sle12-cloud-compute:5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud 6",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud 6",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud 6",
							"product_id": "SUSE OpenStack Cloud 6",
							"cpe": "cpe:/o:suse:suse-openstack-cloud:6"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-pymongo-2.6.3-2.20",
				"full_product_name": {
					"text": "python-pymongo-2.6.3-2.20",
					"product_id": "python-pymongo-2.6.3-2.20"
				}
			},
			{
				"type": "Product Version",
				"name": "python-pymongo-3.0.3-1.1",
				"full_product_name": {
					"text": "python-pymongo-3.0.3-1.1",
					"product_id": "python-pymongo-3.0.3-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-pymongo-3.1.1-1.5",
				"full_product_name": {
					"text": "python-pymongo-3.1.1-1.5",
					"product_id": "python-pymongo-3.1.1-1.5"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-pymongo-3.4.0-1.1",
				"full_product_name": {
					"text": "python3-pymongo-3.4.0-1.1",
					"product_id": "python3-pymongo-3.4.0-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python36-pymongo-3.11.4-1.2",
				"full_product_name": {
					"text": "python36-pymongo-3.11.4-1.2",
					"product_id": "python36-pymongo-3.11.4-1.2"
				}
			},
			{
				"type": "Product Version",
				"name": "python38-pymongo-3.11.4-1.2",
				"full_product_name": {
					"text": "python38-pymongo-3.11.4-1.2",
					"product_id": "python38-pymongo-3.11.4-1.2"
				}
			},
			{
				"type": "Product Version",
				"name": "python39-pymongo-3.11.4-1.2",
				"full_product_name": {
					"text": "python39-pymongo-3.11.4-1.2",
					"product_id": "python39-pymongo-3.11.4-1.2"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-pymongo-2.6.3-2.20",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5"
			},
			{
				"product_reference": "python-pymongo-3.0.3-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud 6"
			},
			{
				"product_reference": "python-pymongo-3.1.1-1.5",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python3-pymongo-3.4.0-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python36-pymongo-3.11.4-1.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python38-pymongo-3.11.4-1.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python39-pymongo-3.11.4-1.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "bson/_cbsonmodule.c in the mongo-python-driver (aka. pymongo) before 2.5.2, as used in MongoDB, allows context-dependent attackers to cause a denial of service (NULL pointer dereference and crash) via vectors related to decoding of an \"invalid DBRef.\"",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2013-2132",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5:python-pymongo-2.6.3-2.20",
						"SUSE OpenStack Cloud 6:python-pymongo-3.0.3-1.1",
						"openSUSE Tumbleweed:python-pymongo-3.1.1-1.5",
						"openSUSE Tumbleweed:python3-pymongo-3.4.0-1.1",
						"openSUSE Tumbleweed:python36-pymongo-3.11.4-1.2",
						"openSUSE Tumbleweed:python38-pymongo-3.11.4-1.2",
						"openSUSE Tumbleweed:python39-pymongo-3.11.4-1.2"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.3",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {}
			}
		}
	]
}
